---
- hosts: all
  become: true

  tasks:
    - name: Updating the apt
      apt: update_cache=yes

    - name: Install aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install nginx
      apt: name=nginx state=latest

      notify:
        - restart nginx

    - name: copying nginx files
      copy:
        src: "{{ playbook_dir }}/nginx_config/config"
        dest: /etc/nginx/sites-available
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Copy Cert Directory to the server
      copy:
        src: "{{ playbook_dir }}/../cert"
        dest: /home/ubuntu/
        owner: ubuntu
        group: ubuntu
        mode: 0400      

    - name: Removing Default file in nginx sites*-available
      command: sudo rm -rf /etc/nginx/sites-available/default

    - name: Removing Default file in nginx sites*-enabled
      command: sudo rm -rf /etc/nginx/sites-enabled/default

    - name: syncing nginx files
      command: sudo ln -s /etc/nginx/sites-available/config /etc/nginx/sites-enabled/config

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded
